import fs from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const svgDirPath = join(__dirname, 'src', 'icons', 'svg');
const outputPath = join(__dirname, 'src', 'icons', 'index.js');

async function generateIconsIndex() {
    
    const svgFiles = (await fs.readdir(svgDirPath)).filter(file => file.endsWith('.svg'));

    let content = `// Automatically generated by script\n\n`;
    svgFiles.forEach(file => {
        const iconName = file.replace('.svg', '');
        const importPath = `./svg/${file}`;
        content += `import ${iconName}Icon from '${importPath}';\n`;
    });

    content += `\nconst icons = {\n`;
    svgFiles.forEach(file => {
        const iconName = file.replace('.svg', '');
        content += `    ${iconName}: ${iconName}Icon,\n`;
    });
    content += `};\n\nexport default icons;\n`;

    // 파일에 쓰기
    await fs.writeFile(outputPath, content);

    console.log(`Icons index file has been generated at ${outputPath}`);
}

generateIconsIndex().catch(console.error);
