// Automatically generated by script

import activitypubIcon from './svg/activitypub.svg';
import actixIcon from './svg/actix.svg';
import aeIcon from './svg/ae.svg';
import aiIcon from './svg/ai.svg';
import aiscriptIcon from './svg/aiscript.svg';
import alpinejsIcon from './svg/alpinejs.svg';
import anacondaIcon from './svg/anaconda.svg';
import androidstudioIcon from './svg/androidstudio.svg';
import angularIcon from './svg/angular.svg';
import ansibleIcon from './svg/ansible.svg';
import apolloIcon from './svg/apollo.svg';
import appleIcon from './svg/apple.svg';
import appwriteIcon from './svg/appwrite.svg';
import archIcon from './svg/arch.svg';
import arduinoIcon from './svg/arduino.svg';
import astroIcon from './svg/astro.svg';
import atomIcon from './svg/atom.svg';
import auIcon from './svg/au.svg';
import autocadIcon from './svg/autocad.svg';
import awsIcon from './svg/aws.svg';
import azulIcon from './svg/azul.svg';
import azureIcon from './svg/azure.svg';
import babelIcon from './svg/babel.svg';
import bashIcon from './svg/bash.svg';
import bevyIcon from './svg/bevy.svg';
import bitbucketIcon from './svg/bitbucket.svg';
import blenderIcon from './svg/blender.svg';
import bootstrapIcon from './svg/bootstrap.svg';
import botsIcon from './svg/bots.svg';
import bsdIcon from './svg/bsd.svg';
import bunIcon from './svg/bun.svg';
import cIcon from './svg/c.svg';
import cassandraIcon from './svg/cassandra.svg';
import clionIcon from './svg/clion.svg';
import clojureIcon from './svg/clojure.svg';
import cloudflareIcon from './svg/cloudflare.svg';
import cmakeIcon from './svg/cmake.svg';
import codepenIcon from './svg/codepen.svg';
import coffeescriptIcon from './svg/coffeescript.svg';
import cppIcon from './svg/cpp.svg';
import crystalIcon from './svg/crystal.svg';
import csIcon from './svg/cs.svg';
import cssIcon from './svg/css.svg';
import cypressIcon from './svg/cypress.svg';
import d3Icon from './svg/d3.svg';
import dartIcon from './svg/dart.svg';
import debianIcon from './svg/debian.svg';
import denoIcon from './svg/deno.svg';
import devtoIcon from './svg/devto.svg';
import discordIcon from './svg/discord.svg';
import discordjsIcon from './svg/discordjs.svg';
import djangoIcon from './svg/django.svg';
import dockerIcon from './svg/docker.svg';
import dotnetIcon from './svg/dotnet.svg';
import dynamodbIcon from './svg/dynamodb.svg';
import eclipseIcon from './svg/eclipse.svg';
import elasticsearchIcon from './svg/elasticsearch.svg';
import electronIcon from './svg/electron.svg';
import elixirIcon from './svg/elixir.svg';
import elysiaIcon from './svg/elysia.svg';
import emacsIcon from './svg/emacs.svg';
import emberIcon from './svg/ember.svg';
import emotionIcon from './svg/emotion.svg';
import expressIcon from './svg/express.svg';
import fastapiIcon from './svg/fastapi.svg';
import fediverseIcon from './svg/fediverse.svg';
import figmaIcon from './svg/figma.svg';
import firebaseIcon from './svg/firebase.svg';
import flaskIcon from './svg/flask.svg';
import flutterIcon from './svg/flutter.svg';
import forthIcon from './svg/forth.svg';
import fortranIcon from './svg/fortran.svg';
import gamemakerstudioIcon from './svg/gamemakerstudio.svg';
import gatsbyIcon from './svg/gatsby.svg';
import gcpIcon from './svg/gcp.svg';
import gherkinIcon from './svg/gherkin.svg';
import gitIcon from './svg/git.svg';
import githubIcon from './svg/github.svg';
import githubactionsIcon from './svg/githubactions.svg';
import gitlabIcon from './svg/gitlab.svg';
import gmailIcon from './svg/gmail.svg';
import goIcon from './svg/go.svg';
import godotIcon from './svg/godot.svg';
import gradleIcon from './svg/gradle.svg';
import grafanaIcon from './svg/grafana.svg';
import graphqlIcon from './svg/graphql.svg';
import gtkIcon from './svg/gtk.svg';
import gulpIcon from './svg/gulp.svg';
import haskellIcon from './svg/haskell.svg';
import haxeIcon from './svg/haxe.svg';
import haxeflixelIcon from './svg/haxeflixel.svg';
import herokuIcon from './svg/heroku.svg';
import hibernateIcon from './svg/hibernate.svg';
import htmlIcon from './svg/html.svg';
import htmxIcon from './svg/htmx.svg';
import ideaIcon from './svg/idea.svg';
import instagramIcon from './svg/instagram.svg';
import ipfsIcon from './svg/ipfs.svg';
import javaIcon from './svg/java.svg';
import jenkinsIcon from './svg/jenkins.svg';
import jestIcon from './svg/jest.svg';
import jqueryIcon from './svg/jquery.svg';
import jsIcon from './svg/js.svg';
import kafkaIcon from './svg/kafka.svg';
import kaliIcon from './svg/kali.svg';
import kotlinIcon from './svg/kotlin.svg';
import ktorIcon from './svg/ktor.svg';
import kubernetesIcon from './svg/kubernetes.svg';
import laravelIcon from './svg/laravel.svg';
import latexIcon from './svg/latex.svg';
import lessIcon from './svg/less.svg';
import linkedinIcon from './svg/linkedin.svg';
import linuxIcon from './svg/linux.svg';
import litIcon from './svg/lit.svg';
import luaIcon from './svg/lua.svg';
import mastodonIcon from './svg/mastodon.svg';
import materialuiIcon from './svg/materialui.svg';
import matlabIcon from './svg/matlab.svg';
import mavenIcon from './svg/maven.svg';
import mdIcon from './svg/md.svg';
import mintIcon from './svg/mint.svg';
import misskeyIcon from './svg/misskey.svg';
import mongodbIcon from './svg/mongodb.svg';
import mysqlIcon from './svg/mysql.svg';
import neovimIcon from './svg/neovim.svg';
import nestjsIcon from './svg/nestjs.svg';
import netlifyIcon from './svg/netlify.svg';
import nextjsIcon from './svg/nextjs.svg';
import nginxIcon from './svg/nginx.svg';
import nimIcon from './svg/nim.svg';
import nixIcon from './svg/nix.svg';
import nodejsIcon from './svg/nodejs.svg';
import notionIcon from './svg/notion.svg';
import npmIcon from './svg/npm.svg';
import nuxtjsIcon from './svg/nuxtjs.svg';
import obsidianIcon from './svg/obsidian.svg';
import ocamlIcon from './svg/ocaml.svg';
import octaveIcon from './svg/octave.svg';
import opencvIcon from './svg/opencv.svg';
import openshiftIcon from './svg/openshift.svg';
import openstackIcon from './svg/openstack.svg';
import p5jsIcon from './svg/p5js.svg';
import perlIcon from './svg/perl.svg';
import phpIcon from './svg/php.svg';
import phpstormIcon from './svg/phpstorm.svg';
import piniaIcon from './svg/pinia.svg';
import pklIcon from './svg/pkl.svg';
import plan9Icon from './svg/plan9.svg';
import planetscaleIcon from './svg/planetscale.svg';
import pnpmIcon from './svg/pnpm.svg';
import postgresIcon from './svg/postgres.svg';
import postmanIcon from './svg/postman.svg';
import powershellIcon from './svg/powershell.svg';
import prIcon from './svg/pr.svg';
import prismaIcon from './svg/prisma.svg';
import processingIcon from './svg/processing.svg';
import prometheusIcon from './svg/prometheus.svg';
import psIcon from './svg/ps.svg';
import pugIcon from './svg/pug.svg';
import pyIcon from './svg/py.svg';
import pycharmIcon from './svg/pycharm.svg';
import pytorchIcon from './svg/pytorch.svg';
import qtIcon from './svg/qt.svg';
import rIcon from './svg/r.svg';
import rabbitmqIcon from './svg/rabbitmq.svg';
import railsIcon from './svg/rails.svg';
import raspberrypiIcon from './svg/raspberrypi.svg';
import reactIcon from './svg/react.svg';
import reactivexIcon from './svg/reactivex.svg';
import redhatIcon from './svg/redhat.svg';
import redisIcon from './svg/redis.svg';
import reduxIcon from './svg/redux.svg';
import regexIcon from './svg/regex.svg';
import remixIcon from './svg/remix.svg';
import replitIcon from './svg/replit.svg';
import riderIcon from './svg/rider.svg';
import robloxstudioIcon from './svg/robloxstudio.svg';
import rocketIcon from './svg/rocket.svg';
import rollupjsIcon from './svg/rollupjs.svg';
import rosIcon from './svg/ros.svg';
import rubyIcon from './svg/ruby.svg';
import rustIcon from './svg/rust.svg';
import sassIcon from './svg/sass.svg';
import scalaIcon from './svg/scala.svg';
import seleniumIcon from './svg/selenium.svg';
import sentryIcon from './svg/sentry.svg';
import sequelizeIcon from './svg/sequelize.svg';
import sketchupIcon from './svg/sketchup.svg';
import sklearnIcon from './svg/sklearn.svg';
import solidityIcon from './svg/solidity.svg';
import solidjsIcon from './svg/solidjs.svg';
import springIcon from './svg/spring.svg';
import sqliteIcon from './svg/sqlite.svg';
import stackoverflowIcon from './svg/stackoverflow.svg';
import styledcomponentsIcon from './svg/styledcomponents.svg';
import sublimeIcon from './svg/sublime.svg';
import supabaseIcon from './svg/supabase.svg';
import svelteIcon from './svg/svelte.svg';
import svgIcon from './svg/svg.svg';
import swiftIcon from './svg/swift.svg';
import symfonyIcon from './svg/symfony.svg';
import tailwindIcon from './svg/tailwind.svg';
import tauriIcon from './svg/tauri.svg';
import tensorflowIcon from './svg/tensorflow.svg';
import terraformIcon from './svg/terraform.svg';
import threejsIcon from './svg/threejs.svg';
import tsIcon from './svg/ts.svg';
import twitterIcon from './svg/twitter.svg';
import ubuntuIcon from './svg/ubuntu.svg';
import unityIcon from './svg/unity.svg';
import unrealIcon from './svg/unreal.svg';
import vIcon from './svg/v.svg';
import valaIcon from './svg/vala.svg';
import vercelIcon from './svg/vercel.svg';
import vimIcon from './svg/vim.svg';
import visualstudioIcon from './svg/visualstudio.svg';
import viteIcon from './svg/vite.svg';
import vitestIcon from './svg/vitest.svg';
import vscodeIcon from './svg/vscode.svg';
import vscodiumIcon from './svg/vscodium.svg';
import vueIcon from './svg/vue.svg';
import vuetifyIcon from './svg/vuetify.svg';
import wasmIcon from './svg/wasm.svg';
import webflowIcon from './svg/webflow.svg';
import webpackIcon from './svg/webpack.svg';
import webstormIcon from './svg/webstorm.svg';
import windicssIcon from './svg/windicss.svg';
import windowsIcon from './svg/windows.svg';
import wordpressIcon from './svg/wordpress.svg';
import workersIcon from './svg/workers.svg';
import xdIcon from './svg/xd.svg';
import yarnIcon from './svg/yarn.svg';
import yewIcon from './svg/yew.svg';
import zigIcon from './svg/zig.svg';

const icons = {
    activitypub: activitypubIcon,
    actix: actixIcon,
    ae: aeIcon,
    ai: aiIcon,
    aiscript: aiscriptIcon,
    alpinejs: alpinejsIcon,
    anaconda: anacondaIcon,
    androidstudio: androidstudioIcon,
    angular: angularIcon,
    ansible: ansibleIcon,
    apollo: apolloIcon,
    apple: appleIcon,
    appwrite: appwriteIcon,
    arch: archIcon,
    arduino: arduinoIcon,
    astro: astroIcon,
    atom: atomIcon,
    au: auIcon,
    autocad: autocadIcon,
    aws: awsIcon,
    azul: azulIcon,
    azure: azureIcon,
    babel: babelIcon,
    bash: bashIcon,
    bevy: bevyIcon,
    bitbucket: bitbucketIcon,
    blender: blenderIcon,
    bootstrap: bootstrapIcon,
    bots: botsIcon,
    bsd: bsdIcon,
    bun: bunIcon,
    c: cIcon,
    cassandra: cassandraIcon,
    clion: clionIcon,
    clojure: clojureIcon,
    cloudflare: cloudflareIcon,
    cmake: cmakeIcon,
    codepen: codepenIcon,
    coffeescript: coffeescriptIcon,
    cpp: cppIcon,
    crystal: crystalIcon,
    cs: csIcon,
    css: cssIcon,
    cypress: cypressIcon,
    d3: d3Icon,
    dart: dartIcon,
    debian: debianIcon,
    deno: denoIcon,
    devto: devtoIcon,
    discord: discordIcon,
    discordjs: discordjsIcon,
    django: djangoIcon,
    docker: dockerIcon,
    dotnet: dotnetIcon,
    dynamodb: dynamodbIcon,
    eclipse: eclipseIcon,
    elasticsearch: elasticsearchIcon,
    electron: electronIcon,
    elixir: elixirIcon,
    elysia: elysiaIcon,
    emacs: emacsIcon,
    ember: emberIcon,
    emotion: emotionIcon,
    express: expressIcon,
    fastapi: fastapiIcon,
    fediverse: fediverseIcon,
    figma: figmaIcon,
    firebase: firebaseIcon,
    flask: flaskIcon,
    flutter: flutterIcon,
    forth: forthIcon,
    fortran: fortranIcon,
    gamemakerstudio: gamemakerstudioIcon,
    gatsby: gatsbyIcon,
    gcp: gcpIcon,
    gherkin: gherkinIcon,
    git: gitIcon,
    github: githubIcon,
    githubactions: githubactionsIcon,
    gitlab: gitlabIcon,
    gmail: gmailIcon,
    go: goIcon,
    godot: godotIcon,
    gradle: gradleIcon,
    grafana: grafanaIcon,
    graphql: graphqlIcon,
    gtk: gtkIcon,
    gulp: gulpIcon,
    haskell: haskellIcon,
    haxe: haxeIcon,
    haxeflixel: haxeflixelIcon,
    heroku: herokuIcon,
    hibernate: hibernateIcon,
    html: htmlIcon,
    htmx: htmxIcon,
    idea: ideaIcon,
    instagram: instagramIcon,
    ipfs: ipfsIcon,
    java: javaIcon,
    jenkins: jenkinsIcon,
    jest: jestIcon,
    jquery: jqueryIcon,
    js: jsIcon,
    kafka: kafkaIcon,
    kali: kaliIcon,
    kotlin: kotlinIcon,
    ktor: ktorIcon,
    kubernetes: kubernetesIcon,
    laravel: laravelIcon,
    latex: latexIcon,
    less: lessIcon,
    linkedin: linkedinIcon,
    linux: linuxIcon,
    lit: litIcon,
    lua: luaIcon,
    mastodon: mastodonIcon,
    materialui: materialuiIcon,
    matlab: matlabIcon,
    maven: mavenIcon,
    md: mdIcon,
    mint: mintIcon,
    misskey: misskeyIcon,
    mongodb: mongodbIcon,
    mysql: mysqlIcon,
    neovim: neovimIcon,
    nestjs: nestjsIcon,
    netlify: netlifyIcon,
    nextjs: nextjsIcon,
    nginx: nginxIcon,
    nim: nimIcon,
    nix: nixIcon,
    nodejs: nodejsIcon,
    notion: notionIcon,
    npm: npmIcon,
    nuxtjs: nuxtjsIcon,
    obsidian: obsidianIcon,
    ocaml: ocamlIcon,
    octave: octaveIcon,
    opencv: opencvIcon,
    openshift: openshiftIcon,
    openstack: openstackIcon,
    p5js: p5jsIcon,
    perl: perlIcon,
    php: phpIcon,
    phpstorm: phpstormIcon,
    pinia: piniaIcon,
    pkl: pklIcon,
    plan9: plan9Icon,
    planetscale: planetscaleIcon,
    pnpm: pnpmIcon,
    postgres: postgresIcon,
    postman: postmanIcon,
    powershell: powershellIcon,
    pr: prIcon,
    prisma: prismaIcon,
    processing: processingIcon,
    prometheus: prometheusIcon,
    ps: psIcon,
    pug: pugIcon,
    py: pyIcon,
    pycharm: pycharmIcon,
    pytorch: pytorchIcon,
    qt: qtIcon,
    r: rIcon,
    rabbitmq: rabbitmqIcon,
    rails: railsIcon,
    raspberrypi: raspberrypiIcon,
    react: reactIcon,
    reactivex: reactivexIcon,
    redhat: redhatIcon,
    redis: redisIcon,
    redux: reduxIcon,
    regex: regexIcon,
    remix: remixIcon,
    replit: replitIcon,
    rider: riderIcon,
    robloxstudio: robloxstudioIcon,
    rocket: rocketIcon,
    rollupjs: rollupjsIcon,
    ros: rosIcon,
    ruby: rubyIcon,
    rust: rustIcon,
    sass: sassIcon,
    scala: scalaIcon,
    selenium: seleniumIcon,
    sentry: sentryIcon,
    sequelize: sequelizeIcon,
    sketchup: sketchupIcon,
    sklearn: sklearnIcon,
    solidity: solidityIcon,
    solidjs: solidjsIcon,
    spring: springIcon,
    sqlite: sqliteIcon,
    stackoverflow: stackoverflowIcon,
    styledcomponents: styledcomponentsIcon,
    sublime: sublimeIcon,
    supabase: supabaseIcon,
    svelte: svelteIcon,
    svg: svgIcon,
    swift: swiftIcon,
    symfony: symfonyIcon,
    tailwind: tailwindIcon,
    tauri: tauriIcon,
    tensorflow: tensorflowIcon,
    terraform: terraformIcon,
    threejs: threejsIcon,
    ts: tsIcon,
    twitter: twitterIcon,
    ubuntu: ubuntuIcon,
    unity: unityIcon,
    unreal: unrealIcon,
    v: vIcon,
    vala: valaIcon,
    vercel: vercelIcon,
    vim: vimIcon,
    visualstudio: visualstudioIcon,
    vite: viteIcon,
    vitest: vitestIcon,
    vscode: vscodeIcon,
    vscodium: vscodiumIcon,
    vue: vueIcon,
    vuetify: vuetifyIcon,
    wasm: wasmIcon,
    webflow: webflowIcon,
    webpack: webpackIcon,
    webstorm: webstormIcon,
    windicss: windicssIcon,
    windows: windowsIcon,
    wordpress: wordpressIcon,
    workers: workersIcon,
    xd: xdIcon,
    yarn: yarnIcon,
    yew: yewIcon,
    zig: zigIcon,
};

export default icons;